config/routes.rb
Rails.application.routes.draw do
	root "product#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "products" => "product#index"
  get "products/new" => "product#new"
  get "products/:id" => "product#show", as: "product"
  get "products/:id/edit" => "product#edit", as: "edit_product"
  patch"products/:id" => "product#update"
  post "products" => "product#create"
  delete "products/:id" => "product#destroy"

  # resource :products

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/asas.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end
	def show
		@product = Product.find(params[:id])
	end
	def edit
		@product = Product.find(params[:id])
	end
	def update
		@product= Product.find(params[:id])
		if @product.update(params[:product].permit(:name, :description, :rating, :inmport_on, :price))
			redirect_to @product
		else
			render:edit
		end
	end
	def create
		product_params = params.require(:product).permit(:name, :description, :rating, :inmport_on, :price)
		@product = Product.new(product_params)
		@product.save
		redirect_to @product
	end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
	def index
		@products = Product.all
	end
	def show
		@product = Product.find(params[:id])
	end
	def edit
		@product = Product.find(params[:id])
	end
	def update
		@product= Product.find(params[:id])
		if @product.update(params[:product].permit(:name, :description, :rating, :inmport_on, :price))
			redirect_to @product
		else
			render:edit
		end
	end
	def new
		@product = Product.new
	end

	def create
		product_params= params.require(:product).permit(:name, :description, :rating, :inmport_on, :price)
		@product= Product.new(product_params)
		@product.save
		redirect_to @product
	end
	 def destroy
	 	@product= Product.find(params[:id])
	 	@product.destroy
		redirect_to products_url	 	
	 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
	def format_price(product)
		if product.price<20
			content_tag(:strong, 'Flop!')
		else
			number_to_currency(product.price)
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product/edit.html.erb
<h1> Editing Product: <%= @product.name %></h1>
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :rating %><br/>
    <%= f.text_field :rating, size: 5 %>
  </p>
  <p>
    <%= f.label :imported_on %><br/>
    <%= f.date_field :imported_on %>
  </p>
  <p>
    <%= f.label :price %><br/>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/product/index.html.erb
<h1><%= pluralize(@products.size, 'Product') %></h1>
	<%= link_to("Add New Product", products_new_path) %>
<ul>
<% @products.each do |product| %>
  <li><strong><%= link_to(product.name, product_path(product))%></strong>
  			 	<p><%= truncate(product.description, length: 30, separator: '' )%></p>
  			 	
  			 	<p>(<%=product.rating %>)</p>

  				<p><%= format_price(product) %></p>

  				<p><%= product.imported_on %> </p>

  </li>
<% end %>
</ul>

app/views/product/new.html.erb
<h1>Create Product</h1>
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :rating %><br/>
    <%= f.text_field :rating, size: 4 %>
  </p>
  <p>
    <%= f.label :imported_on %><br/>
    <%= f.date_select :imported_on %>
  </p>
  <p>
    <%= f.label :price %><br/>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/product/show.html.erb
<article>
	<header>
		<h1><%= @product.name %></h1>
	</header>
	<h2>Price</h2>
	<p>
		<%= format_price(@product) %>
	</p>
	<h2>Description</h2>
	<p>
		<%= @product.description %>
	</p>
	<h3>Rating</h3>
	<p>
		<%= @product.rating %>
	</p>
	<h3>Imported On</h3>
	<p>
		<%= @product.imported_on %>
	</p>
	<nav>
		<%= link_to("All Product", root_path) %>
		<%= link_to("Edit", edit_product_path(@product)) %>
		<%=  link_to "Delete", product_path(@product), method: :delete, data: {confirm:"Are you sure?"} %>	
	</nav>
	
</article>